site_name: Software Architecture Labs
site_description: Les Travaux Pratiques du cours Architectures Logicielles
site_author: Hela CHIKHAOUI & Lilia SFAXI
site_url: http://INSATunisia.github.io/TP-ArchLog/

# Repository
repo_name: INSATunisia/TP-ArchLog
repo_url: https://github.com/INSATunisia/TP-ArchLog

# Copyright
copyright: 'Copyright &copy; 2022 - 2023 Hela Chikhaoui & Lilia Sfaxi'

# Theme directory
plugins:
  - search
  - autolinks  
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  favicon: img/favicon.ico
  logo: "img/logo.png"
  font: 
    text: 'Questrial'
    code: 'Source Code Pro'
  palette:
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      accent: teal
      primary: teal
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: teal
      primary: teal


extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'

# Page tree
pages:
   - Software Architecure Labs: 'index.md'
   - Lab0 - OOP Design Patterns: 'tp0.md'
  #  - Lab1 - The SOLID principles: 'tp1.md'
  #  - Lab2 - MV* Architectures : 'tp2.md'
  #  - Lab3 - Microservices Architecture : 'tp3.md'
  #  #- DS - Microservices avec Spring Boot et Spring Cloud : 'tp-ds.md'
  #  - Lab4 - Towards more reactive microservices : 'tp4.md'
   #- Lab5 - A hybrid software architecture : 'tp5.md'

extra_javascript: []
extra_css: []
use_directory_urls: true

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
