site_name: Software Architecture Labs
site_description: Les Travaux Pratiques du cours Architectures Logicielles
site_author: Hela Chikhaoui
site_url: http://INSATunisia.github.io/TP-ArchLog/

# Repository
repo_name: INSATunisia/TP-ArchLog
repo_url: https://github.com/INSATunisia/TP-ArchLog

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Hela Chikhaoui'

# Theme directory
plugins:
  - search
  - autolinks  
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: "theme"
  logo: "img/logo.png"
  palette:
    accent: teal
    primary: teal
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'

# Page tree
nav:
   - 'index.md'
   - Lab1 - The SOLID principles: 'tp1.md'
   - Lab2 - MV* Architectures : 'tp2.md'
   - Lab3 - Microservices Architecture : 'tp3.md'

extra_javascript: []
extra_css: []
use_directory_urls: true

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
